version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: 'berea6922'
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql
            - './initial.sql:/docker-entrypoint-initdb.d/initial.sql'
    php:
        container_name: php
        build:
            context: ./images/php
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "9000:9000"
        volumes:
            - ./source:/var/www/html
    nginx:
        container_name: nginx
        build:
            context: ./images/nginx
            dockerfile: Dockerfile
        volumes:
            - ./source:/var/www/html
            - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"